# Generated by Django 5.2 on 2026-03-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField()),
                ('is_email_confired', models.BooleanField(default=False)),
                ('email_confirm_token', models.CharField(default='')),
                ('email_confirm_at', models.DateTimeField(blank=True, null=True)),
                ('reset_password_token', models.CharField(default='')),
                ('reset_password_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
